version: 1
disable_existing_loggers: True

formatters:
    abkFormatterShort:
        format: '[%(asctime)s]:[%(funcName)s]:[%(levelname)s]: %(message)s'
        datefmt: '%Y%m%d %H:%M:%S'
    abkFormatterLong:
        format: '[%(asctime)s]:[%(thread)d]:[%(funcName)s]:[%(name)s][%(levelname)s]: %(message)s'
        datefmt: '%Y%m%d %H:%M:%S'

handlers:
    consoleHandler:
        class: logging.StreamHandler
        level: WARNING
        formatter: abkFormatterShort
        stream: ext://sys.stdout
    fileHandler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: abkFormatterLong
        filename: logs/eir.log
        maxBytes: 1048576  # 1MB
        backupCount: 10
    queueHandler:
        class: logging.handlers.QueueHandler
        level: WARNING
        queue: ext://queue.Queue

loggers:
    root:
        level: WARNING
        handlers: [consoleHandler]
    consoleLogger:
        level: WARNING
        handlers: [consoleHandler]
        qualname: consoleLogger
        propagate: no
    fileLogger:
        level: WARNING
        handlers: [fileHandler]
        qualname: fileLogger
        propagate: no
    threadedConsoleLogger:
        level: WARNING
        handlers: [queueHandler]
        qualname: threadedConsoleLogger
        propagate: no
    threadedFileLogger:
        level: WARNING
        handlers: [queueHandler]
        qualname: threadedFileLogger
        propagate: no

root:
    level: WARNING
    handlers: [consoleHandler]
