"""Build-time constants generated by build script."""

VERSION = "0.3.5"
NAME = "eir"
LICENSE = "MIT"
KEYWORDS = ["exif", "images", "pictures", "rename", "convert"]
AUTHORS = [{"name": "ABK", "email": "alexbigkid@users.noreply.github.com"}]
MAINTAINERS = [{"name": "ABK", "email": "alexbigkid@users.noreply.github.com"}]
