name: Release Pipeline

on:
  push:
    tags:
      - 'patch'
      - 'minor'
      - 'major'

jobs:
  # First job: Run tests and checks
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify main branch
        run: |
          # Get the commit SHA that the tag points to
          tag_commit=$(git rev-list -n 1 ${{ github.ref_name }})
          # Get the latest commit on main branch
          git fetch origin main
          main_commit=$(git rev-parse origin/main)
          
          if [ "$tag_commit" != "$main_commit" ]; then
            echo "❌ Error: Tag must point to the latest commit on main branch"
            echo "Tag commit: $tag_commit"
            echo "Main commit: $main_commit"
            exit 1
          fi
          echo "✅ Confirmed: Tag points to latest main branch commit"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest --cov=eir --cov-report=xml

      - name: Run linting
        run: |
          uv run ruff check
          uv run ruff format --check

  # Second job: Version bump (depends on test success)
  version-bump:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      version_tag: ${{ steps.bump.outputs.version_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Get current version and bump
        id: bump
        run: |
          # Read current version from pyproject.toml
          current_version=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $current_version"
          
          # Validate current version format
          if [[ ! "$current_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Error: Invalid version format: $current_version"
            exit 1
          fi
          
          # Parse version components
          IFS='.' read -r major minor patch <<< "$current_version"
          
          # Determine new version based on tag
          tag_name="${{ github.ref_name }}"
          echo "Release type: $tag_name"
          
          case $tag_name in
            "major")
              new_major=$((major + 1))
              new_minor=0
              new_patch=0
              ;;
            "minor")
              new_major=$major
              new_minor=$((minor + 1))
              new_patch=0
              ;;
            "patch")
              new_major=$major
              new_minor=$minor
              new_patch=$((patch + 1))
              ;;
            *)
              echo "❌ Error: Invalid release tag: $tag_name"
              exit 1
              ;;
          esac
          
          new_version="${new_major}.${new_minor}.${new_patch}"
          version_tag="v${new_version}"
          
          echo "New version: $new_version"
          echo "Version tag: $version_tag"
          
          # Validate new version format
          if [[ ! "$new_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Error: Generated invalid version: $new_version"
            exit 1
          fi
          
          # Update pyproject.toml
          sed -i "s/^version = \".*\"/version = \"$new_version\"/" pyproject.toml
          
          # Set outputs
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "version_tag=$version_tag" >> $GITHUB_OUTPUT

      - name: Commit version bump and create release tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "🔖 Bump version to ${{ steps.bump.outputs.new_version }}"
          git tag ${{ steps.bump.outputs.version_tag }}
          git push origin HEAD:main
          git push origin ${{ steps.bump.outputs.version_tag }}

      - name: Delete trigger tag
        run: |
          # Delete the original trigger tag to keep repo clean
          git push --delete origin ${{ github.ref_name }}

  # Third job: Build binaries (depends on version-bump success)
  build:
    needs: [test, version-bump]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main  # Get the updated version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install UV (Unix)
        if: runner.os != 'Windows'
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install UV (Windows)
        if: runner.os == 'Windows'
        run: |
          irm https://astral.sh/uv/install.ps1 | iex
          echo "$env:USERPROFILE\.cargo\bin" >> $env:GITHUB_PATH

      - name: Install dependencies
        run: uv sync --dev

      - name: Build binary
        run: uv run python build.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eir-${{ needs.version-bump.outputs.new_version }}-${{ runner.os }}
          path: |
            dist/eir-*
            !dist/*.spec

  # Fourth job: Create GitHub release (depends on all builds)
  release:
    needs: [test, version-bump, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find ./artifacts -name "eir-*" -type f -exec cp {} ./release-assets/ \;
          ls -la ./release-assets/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.version-bump.outputs.version_tag }}
          name: "Eir ${{ needs.version-bump.outputs.new_version }}"
          body: |
            ## 🚀 Eir ${{ needs.version-bump.outputs.new_version }}
            
            ### 📦 Downloads
            - **macOS**: `eir-${{ needs.version-bump.outputs.new_version }}-macos-universal`
            - **Linux**: `eir-${{ needs.version-bump.outputs.new_version }}-linux-x86_64`  
            - **Windows**: `eir-${{ needs.version-bump.outputs.new_version }}-windows-amd64.exe`
            
            ### 🔧 Installation
            
            **macOS/Linux:**
            ```bash
            # Download the binary for your platform
            chmod +x eir-${{ needs.version-bump.outputs.new_version }}-<platform>
            sudo mv eir-${{ needs.version-bump.outputs.new_version }}-<platform> /usr/local/bin/eir
            ```
            
            **Windows:**
            ```cmd
            # Download eir-${{ needs.version-bump.outputs.new_version }}-windows-amd64.exe
            # Add to your PATH or run directly
            ```
            
            ### 📝 Changes
            - Automated release build for version ${{ needs.version-bump.outputs.new_version }}
            - Multi-platform binaries (macOS, Linux, Windows)
            - See commit history for detailed changes
            
            ---
            🤖 Generated with [Claude Code](https://claude.ai/code)
          files: ./release-assets/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}